### ISSUE TITLE
GCC 6 compilation

### ISSUE THREAD

**Issue by timocafe** [akosenkov/bind#1]
hello Alex, 
evaluating your work, I still hope I could use it. Start bad I am not able to compile: 

```
         inliner::latch(new kernel(), args...);
                       ^
```

utils/bind.hpp:2757:27: error: it must be the address of a function with external linkage

any ideas ?

best

**Comment by akosenkov** [comment]
I have never tried gcc 6 but can you send me your example so I can check?

**Comment by timocafe** [comment]
Well I am just trying to compile the basic example (Array) , by the way I fork your project and I replug OMP (from ambient).

g++-6 -o array.node array.cpp -O3 -std=c++11
In file included from array.cpp:1:0:
utils/bind.hpp: In instantiation of 'static void bind::kernel<D, K>::expand_spawn(bind::index_sequence<I ...>, Args& ...) [with long unsigned int ...I = {0ul, 1ul, 2ul, 3ul}; Args = {bind::proxy_iterator<bind::array<int, bind::snapshot> >, bind::proxy_iterator<bind::array<int, bind::snapshot> >, int (*)(), void (*)(bind::proxy_iterator<bind::array<int, bind::snapshot> >, bind::proxy_iterator<bind::array<int, bind::snapshot> >, int (*)())}; bind::device D = (bind::device)0; K = bind::lambda_kernel<(bind::device)0, false, void (*)(bind::proxy_iterator<bind::array<int, bind::snapshot> >, bind::proxy_iterator<bind::array<int, bind::snapshot> >, int (*)()), bind::proxy_iterator<bind::array<int, bind::snapshot> >, bind::proxy_iterator<bind::array<int, bind::snapshot> >, int (*)()>]':
utils/bind.hpp:2761:25:   required from 'static void bind::kernel<D, K>::spawn(Args&& ...) [with Args = {bind::proxy_iterator<bind::array<int, bind::snapshot> >, bind::proxy_iterator<bind::array<int, bind::snapshot> >, int (*)(), void (*)(bind::proxy_iterator<bind::array<int, bind::snapshot> >, bind::proxy_iterator<bind::array<int, bind::snapshot> >, int (*)())}; bind::device D = (bind::device)0; K = bind::lambda_kernel<(bind::device)0, false, void (*)(bind::proxy_iterator<bind::array<int, bind::snapshot> >, bind::proxy_iterator<bind::array<int, bind::snapshot> >, int (*)()), bind::proxy_iterator<bind::array<int, bind::snapshot> >, bind::proxy_iterator<bind::array<int, bind::snapshot> >, int (*)()>]'
utils/bind.hpp:2794:64:   required from 'static void bind::lambda_kernel<D, false, F, T ...>::dispatch(L&, Args&& ...) [with L = void (*)(bind::proxy_iterator<bind::array<int, bind::snapshot> >, bind::proxy_iterator<bind::array<int, bind::snapshot> >, int (*)()); Args = {bind::proxy_iterator<bind::array<int, bind::snapshot> >, bind::proxy_iterator<bind::array<int, bind::snapshot> >, int (*)()}; bind::device D = (bind::device)0; F = void (*)(bind::proxy_iterator<bind::array<int, bind::snapshot> >, bind::proxy_iterator<bind::array<int, bind::snapshot> >, int (*)()); T = {bind::proxy_iterator<bind::array<int, bind::snapshot> >, bind::proxy_iterator<bind::array<int, bind::snapshot> >, int (*)()}]'
utils/bind.hpp:2836:92:   required from 'void bind::decorator<D, R (*)(L ...)>::operator()(T&& ...) [with T = {bind::proxy_iterator<bind::array<int, bind::snapshot> >, bind::proxy_iterator<bind::array<int, bind::snapshot> >, int (*)()}; bind::device D = (bind::device)0; L = {bind::proxy_iterator<bind::array<int, bind::snapshot> >, bind::proxy_iterator<bind::array<int, bind::snapshot> >, int (*)()}; R = void]'
utils/bind.hpp:2848:33:   required from 'void bind::cpu(L, Args&& ...) [with L = void (*)(bind::proxy_iterator<bind::array<int, bind::snapshot> >, bind::proxy_iterator<bind::array<int, bind::snapshot> >, int (*)()); Args = {bind::proxy_iterator<bind::array<int, bind::snapshot> >, bind::proxy_iterator<bind::array<int, bind::snapshot> >, int (*)()}]'
array.cpp:17:107:   required from here
utils/bind.hpp:2757:27: error: '(bind::lambda_kernel<(bind::device)0, false, void (*)(bind::proxy_iterator<bind::array<int, bind::snapshot> >, bind::proxy_iterator<bind::array<int, bind::snapshot> >, int (*)()), bind::proxy_iterator<bind::array<int, bind::snapshot> >, bind::proxy_iterator<bind::array<int, bind::snapshot> >, int (*)()>::ftype)bind::lambda_kernel<(bind::device)0, false, void (*)(bind::proxy_iterator<bind::array<int, bind::snapshot> >, bind::proxy_iterator<bind::array<int, bind::snapshot> >, int (*)()), bind::proxy_iterator<bind::array<int, bind::snapshot> >, bind::proxy_iterator<bind::array<int, bind::snapshot> >, int (*)()>::c' is not a valid template argument for type 'void (*)(bind::proxy_iterator<bind::array<int, bind::snapshot> >, bind::proxy_iterator<bind::array<int, bind::snapshot> >, int (*)(), void (*&)(bind::proxy_iterator<bind::array<int, bind::snapshot> >, bind::proxy_iterator<bind::array<int, bind::snapshot> >, int (*)()))'
             inliner::latch(new kernel(), args...);

**Comment by akosenkov** [comment]
Ok, I will check gcc 6 at some point (don't have it anywhere yet). For now I would try another gcc version though.

**Comment by timocafe** [comment]
I get the same issue with llvm but simple error message 


bash-3.2$ g++ array.cpp -std=c++14 -DBIND_THREADING=NOTHING
array.cpp:18:9: error: no matching function for call to 'cpu'
        bind::cpu(std::sort<array<int>::iterator>, A.begin(), A.end());
        ^~~~~~~~~
./utils/bind.hpp:2847:10: note: candidate template ignored: couldn't infer template argument 'L'
    void cpu(L l, Args&& ... args){
         ^
./utils/bind.hpp:2757:13: error: non-type template argument for template parameter of pointer type 'void (*)(bind::proxy_iterator<bind::array<int, bind::snapshot> >, bind::proxy_iterator<bind::array<int, bind::snapshot> >, int (*)(), void
      (*&)(bind::proxy_iterator<bind::array<int, bind::snapshot> >, bind::proxy_iterator<bind::array<int, bind::snapshot> >, int (*)()))' must have its address taken
            inliner::latch(new kernel(), args...);

**Comment by akosenkov** [comment]
Can you try adding &?
I.e. bind::cpu(&std::sort<array<int>::iterator>, A.begin(), A.end());

**Comment by akosenkov** [comment]
`bind::cpu(std::sort<array<int>::iterator>, A.begin(), A.end());
`

**Comment by akosenkov** [comment]
`bind::cpu(&std::sort<array<int>::iterator>, A.begin(), A.end());
`

**Comment by timocafe** [comment]
fail but I am going in holiday cu in 10  days !

++t

**Comment by akosenkov** [comment]
Have a good one! 👍

**Comment by akosenkov** [comment]
fixed

**Comment by timocafe** [comment]
Yeah I get the first ticket +1
